# Documentation at http://goreleaser.com
project_name: hammer
before:
  hooks:
  - go mod download
builds:
- main: ./main.go
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  env:
  - GO111MODULE=on
  - CGO_ENABLED=0
archives:
- name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
  - none*
changelog:
