---
language: go

go:
- "1.12"

env:
- GO111MODULE=on

install:
- go get github.com/onsi/ginkgo/ginkgo
- go mod download

script:
- ginkgo -r .

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
